using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace StockHub.Infrastructure.Reports;

public record SalesReportItem(
    string OrderNumber,
    string CustomerName,
    DateTime OrderDate,
    string Status,
    List<SalesReportLineItem> Items,
    decimal TotalAmount
);

public record SalesReportLineItem(
    string ProductName,
    string ProductSku,
    decimal Quantity,
    decimal UnitPrice,
    decimal TotalPrice
);

public class SalesReportDocument(
    List<SalesReportItem> orders,
    string generatedBy) : IDocument
{
    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(30);
            page.DefaultTextStyle(x => x.FontSize(9).FontFamily("Arial"));

            page.Header().Element(ComposeHeader);
            page.Content().Element(ComposeContent);
            page.Footer().Element(ComposeFooter);
        });
    }

    private void ComposeHeader(IContainer container)
    {
        container.Column(col =>
        {
            col.Item().Row(row =>
            {
                row.RelativeItem().Column(c =>
                {
                    c.Item().Text("Sales Report")
                        .FontSize(20).Bold().FontColor(Colors.Grey.Darken3);
                    c.Item().Text("DvNET Systems — StockHub")
                        .FontSize(9).FontColor(Colors.Grey.Medium);
                });
                row.ConstantItem(200).AlignRight().Column(c =>
                {
                    c.Item().Text($"Generated: {DateTime.UtcNow:MMM d, yyyy HH:mm} UTC")
                        .FontSize(8).FontColor(Colors.Grey.Medium);
                    c.Item().Text($"Generated by: {generatedBy}")
                        .FontSize(8).FontColor(Colors.Grey.Medium);
                    c.Item().Text($"Period: All time")
                        .FontSize(8).FontColor(Colors.Grey.Medium);
                });
            });

            col.Item().PaddingTop(8).BorderBottom(2).BorderColor(Colors.Blue.Medium);

            // Summary bar
            col.Item().PaddingTop(10).Row(row =>
            {
                SummaryBox(row, "Total Orders", orders.Count.ToString());
                SummaryBox(row, "Completed",
                    orders.Count(o => o.Status == "Completed").ToString(),
                    Colors.Green.Darken2);
                SummaryBox(row, "Pending",
                    orders.Count(o => o.Status is "Draft" or "Confirmed").ToString(),
                    Colors.Orange.Darken2);
                SummaryBox(row, "Total Revenue",
                    orders.Where(o => o.Status == "Completed")
                          .Sum(o => o.TotalAmount).ToString("C2"),
                    Colors.Blue.Darken2);
            });
        });
    }

    private static void SummaryBox(RowDescriptor row, string label, string value,
        string? valueColor = null)
    {
        row.RelativeItem().Border(1).BorderColor(Colors.Grey.Lighten2)
            .Padding(8).Column(c =>
            {
                c.Item().Text(label).FontSize(7).FontColor(Colors.Grey.Medium);
                c.Item().Text(value).FontSize(13).Bold()
                    .FontColor(valueColor ?? Colors.Grey.Darken3);
            });
    }

    private void ComposeContent(IContainer container)
    {
        container.PaddingTop(15).Column(col =>
        {
            foreach (var order in orders)
            {
                col.Item().PaddingBottom(12).Column(orderCol =>
                {
                    // Order header
                    orderCol.Item()
                        .Background(order.Status == "Completed"
                            ? Colors.Green.Lighten4
                            : Colors.Grey.Lighten4)
                        .Padding(6)
                        .Row(row =>
                        {
                            row.RelativeItem().Text(t =>
                            {
                                t.Span($"{order.OrderNumber}  ").Bold().FontSize(9);
                                t.Span($"· {order.CustomerName}").FontColor(Colors.Grey.Darken1);
                            });
                            row.ConstantItem(100).AlignCenter()
                                .Text(order.Status)
                                .FontSize(8).Bold()
                                .FontColor(order.Status == "Completed"
                                    ? Colors.Green.Darken2
                                    : order.Status == "Cancelled"
                                        ? Colors.Red.Medium
                                        : Colors.Orange.Darken2);
                            row.ConstantItem(80).AlignRight()
                                .Text(order.OrderDate.ToString("MMM d, yyyy"))
                                .FontSize(8).FontColor(Colors.Grey.Medium);
                            row.ConstantItem(80).AlignRight()
                                .Text(order.TotalAmount.ToString("C2"))
                                .Bold().FontSize(9);
                        });

                    // Items table
                    orderCol.Item().Table(table =>
                    {
                        table.ColumnsDefinition(cols =>
                        {
                            cols.RelativeColumn(3); // Product
                            cols.RelativeColumn(1); // SKU
                            cols.RelativeColumn(1); // Qty
                            cols.RelativeColumn(1); // Unit Price
                            cols.RelativeColumn(1); // Total
                        });

                        // Header
                        foreach (var h in new[] { "Product", "SKU", "Qty", "Unit Price", "Total" })
                        {
                            table.Cell().Background(Colors.Grey.Lighten3).Padding(4)
                                .Text(h).FontSize(7).Bold().FontColor(Colors.Grey.Darken2);
                        }

                        // Rows
                        foreach (var item in order.Items)
                        {
                            table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten3)
                                .Padding(4).Text(item.ProductName).FontSize(8);
                            table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten3)
                                .Padding(4).Text(item.ProductSku).FontSize(8)
                                .FontColor(Colors.Grey.Medium);
                            table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten3)
                                .Padding(4).AlignRight().Text(item.Quantity.ToString("N2")).FontSize(8);
                            table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten3)
                                .Padding(4).AlignRight().Text(item.UnitPrice.ToString("C2")).FontSize(8);
                            table.Cell().BorderBottom(1).BorderColor(Colors.Grey.Lighten3)
                                .Padding(4).AlignRight().Text(item.TotalPrice.ToString("C2"))
                                .FontSize(8).Bold();
                        }
                    });
                });
            }
        });
    }

    private void ComposeFooter(IContainer container)
    {
        container.Row(row =>
        {
            row.RelativeItem()
                .Text($"Total Orders: {orders.Count}  |  " +
                      $"Completed Revenue: " +
                      $"{orders.Where(o => o.Status == "Completed").Sum(o => o.TotalAmount):C2}")
                .FontSize(9).FontColor(Colors.Grey.Darken1);

            row.RelativeItem().AlignCenter().Text(x =>
            {
                x.Span("Page ").FontSize(9);
                x.CurrentPageNumber().FontSize(9);
                x.Span(" of ").FontSize(9);
                x.TotalPages().FontSize(9);
            });

            row.RelativeItem().AlignRight()
                .Text("StockHub · DvNET Systems")
                .FontSize(8).FontColor(Colors.Grey.Medium);
        });
    }
}
